defaults:
    - _self_
    - agent: sac

algo_name: sac

#env
env: dog_stand

# Basic setup
device: cuda
seed: 1

# training
num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 5000
eval_frequency: 10000
num_eval_episodes: 10

# unsupervise
num_unsup_steps: 0
topK: 5
reset_update: 100

# logger
log_frequency: 10000
log_save_wandb: true

# video recorder
save_video: false
save_model: true

# wandb
run_group: ''
exp_name: ${run_group}_s${seed}
notes: ''
save_dir: '/mnt/workspace/hrl_bench/preference_rl/Rating-based-Reinforcement-Learning/logs_metaworld/${env}'

# debug
debug: false

# hydra configuration
hydra:
    output_subdir: null
    run:
        dir: ${save_dir}/${run_group}/${exp_name}
